services:
  - type: web
    name: truck-tracker
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: KEEP_ALIVE_URL
        value: https://trucktracker-ux1i.onrender.com/api/health
